<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_(UTC0300) AsiaBahrain</name>
   <tag></tag>
   <elementGuidId>488aa8ea-9853-4b97-931c-30a27ccee95e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#assigned_to-option-245</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='(UTC+03:00) Asia/Bahrain']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;(UTC+03:00) Asia/Bahrain&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>eae77e46-708c-44e2-9176-20c25f40d12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f0ba1f0d-918d-45d5-b140-f7da3b6f63c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2bb3f8f9-a9c1-49f9-8be0-932906f7a334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assigned_to-option-245</value>
      <webElementGuid>3af9ccaf-c437-473b-8a22-9b2008af3991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>245</value>
      <webElementGuid>20c93b74-b764-4c66-9a5a-963eeb6566f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c12d85a4-96cd-4be0-9f6d-9151eedcb6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ff5f77b9-5a7d-407d-b182-e4a368c3ba3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>16d7bb84-d4e2-4798-aacf-052d8af96784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(UTC+03:00) Asia/Bahrain</value>
      <webElementGuid>deeca743-5b13-46ea-9c2a-7c0bf0cd96c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assigned_to-option-245&quot;)</value>
      <webElementGuid>aa7428a9-0581-4501-96db-fc238afb88fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='assigned_to-option-245']</value>
      <webElementGuid>3b84146f-6fea-481a-aae0-911d9f8702ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='assigned_to-listbox']/li[246]</value>
      <webElementGuid>26dc2d12-9f9a-4f6f-85f5-8cd0a57776d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(UTC+03:00) Asia/Baghdad'])[1]/following::li[1]</value>
      <webElementGuid>2e0b882b-7472-4ce0-9012-4ff84980ea36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(UTC+05:00) Asia/Atyrau'])[1]/following::li[2]</value>
      <webElementGuid>8c9e1ee0-50e7-44af-a083-32d2057345e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(UTC+04:00) Asia/Baku'])[1]/preceding::li[1]</value>
      <webElementGuid>9700e3f2-9ccf-4c9e-b81e-a020444e2dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(UTC+07:00) Asia/Bangkok'])[1]/preceding::li[2]</value>
      <webElementGuid>2682d5e2-5e81-4bdf-ab4f-983cddbbf8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(UTC+03:00) Asia/Bahrain']/parent::*</value>
      <webElementGuid>62bb842b-5b7d-4ff7-977b-e6d6d74e0e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[246]</value>
      <webElementGuid>0b3bb571-4a7a-440d-9514-5937cd19aa0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'assigned_to-option-245' and (text() = '(UTC+03:00) Asia/Bahrain' or . = '(UTC+03:00) Asia/Bahrain')]</value>
      <webElementGuid>e04bf0d5-d0c0-4f40-b232-e90cc613bfe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
