<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Image settings_default-patch  multisele_f5bdd9_1</name>
   <tag></tag>
   <elementGuidId>44c1510a-c782-4d9d-a89d-ac5c1fa930f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.default-patch.multiselect-patch.show-subcell-lable.enabled.patch-menu-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbc_33916_18400.jpg-patch-image-reivew']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;wbc_33916_18400\.jpg-patch-image-reivew&quot;] div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0490209a-c738-4183-84c2-678afc70ba4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> default-patch  multiselect-patch show-subcell-lable  enabled patch-menu-container</value>
      <webElementGuid>0009cd89-bc9b-46bc-8d2a-5b8ee686d667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbc_33916_18400.jpg-patch-image-reivew&quot;)/div[@class=&quot;patch-img-container multiselect-patch&quot;]/div[@class=&quot;default-patch  multiselect-patch show-subcell-lable  enabled patch-menu-container&quot;]</value>
      <webElementGuid>4c6a57c9-5f1d-4824-9663-7311cfa180bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbc_33916_18400.jpg-patch-image-reivew']/div/div</value>
      <webElementGuid>be120c98-55c4-4a11-ab3c-ed676274242a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image settings'])[1]/following::div[21]</value>
      <webElementGuid>d5a123f9-a8c7-47aa-bfb2-84a55c1fdf65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of WBCs counted is &lt;200. Differential count might not be accurate'])[1]/following::div[27]</value>
      <webElementGuid>bd5c8f5d-4e2a-4930-ace4-eac7212a1048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Band Forms'])[2]/preceding::div[90]</value>
      <webElementGuid>f73c238c-be0f-4e7d-833e-10d32b005797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Band Forms'])[3]/preceding::div[97]</value>
      <webElementGuid>99f848ef-cc4a-4589-8a79-184d58cd1cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/div/div</value>
      <webElementGuid>9b10cd0f-4876-4254-ab77-ea21d3659407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbc_15752_9532.jpg-patch-image-reivew']/div/div</value>
      <webElementGuid>8427a519-f98a-46d7-8903-50ba3e015160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
