<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Maximum 50 charaters allowed</name>
   <tag></tag>
   <elementGuidId>82e0dfd1-1888-4f9b-ab74-acee4970990c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Maximum 50 charaters allowed' or . = 'Maximum 50 charaters allowed')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75091de2-d4b3-484c-82df-f5c193597f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error-message</value>
      <webElementGuid>8cfbe05a-db57-461f-b0b6-890b24b5c744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maximum 50 charaters allowed</value>
      <webElementGuid>037ccd18-7d0f-4657-be95-94ba74cc53dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;error-message&quot;]</value>
      <webElementGuid>1118c0ce-fb7a-4fdd-bd8e-7b9fe0c15214</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Maximum 50 charaters allowed' or . = 'Maximum 50 charaters allowed')]</value>
      <webElementGuid>4cbcfa2a-aa46-4745-83a6-b1320995769e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
