<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_FOV1 10_clickable</name>
   <tag></tag>
   <elementGuidId>5589e535-fb71-456f-9734-ce074cf578ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.clickable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/div[3]/div/div/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^FOV 1 / 10Platelet ClumpsShow annotations$/ >> internal:role=img >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bbfdbe00-e64f-4640-ad33-8115fb3491b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/next.svg</value>
      <webElementGuid>e2dbab2b-ecdb-4fc2-9a7b-6c6661a8a184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickable</value>
      <webElementGuid>0c287174-6436-404b-9ccf-de9dce8857e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;review-body&quot;]/div[@class=&quot;review-selected-category&quot;]/div[@class=&quot;split-view-contaier&quot;]/div[@class=&quot;split-view-viewer-section&quot;]/div[@class=&quot;fov-selection&quot;]/div[@class=&quot;fov-change&quot;]/img[@class=&quot;clickable&quot;]</value>
      <webElementGuid>c4f15b35-a60a-4d5d-b3a2-bc34bdd3eefa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div[3]/div/div/img[2]</value>
      <webElementGuid>1623a67d-3b84-4ada-bc0a-47ce0e49e1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img[2]</value>
      <webElementGuid>5e1c1536-6c32-4046-87ed-625c506c3e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/icons/next.svg']</value>
      <webElementGuid>bd612826-cf29-4d11-acd8-a0a231a45391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
