<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multiplication factor_outlined-error-helper-text</name>
   <tag></tag>
   <elementGuidId>cdeda399-a2f1-4a11-bf82-84ef98a31c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#outlined-error-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='outlined-error-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#outlined-error-helper-text</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cabf45ba-225f-4173-ad83-c3d35a4b7be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd57acd5-7e06-4587-abb1-f35b5f52339a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-text-field error</value>
      <webElementGuid>d392ebfb-3ff5-4784-b1ce-961a135a9d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-error-helper-text</value>
      <webElementGuid>fe0a4621-80d7-40ac-bf01-113eab29861d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outlined-error-helper-text&quot;)</value>
      <webElementGuid>634d1c9d-5ef7-43c2-98eb-39f59ab1f83d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outlined-error-helper-text']</value>
      <webElementGuid>05d3a5dd-4a70-4091-bdd8-2db8bb840cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>8d4f72f9-b7e2-476b-836f-988679d54836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>8307ccd1-4c33-4286-a205-d549a73ef2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'outlined-error-helper-text']</value>
      <webElementGuid>208f4e5c-8997-4065-aab9-bc92ea189e0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
