<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wbc image first neutrophile (2)</name>
   <tag></tag>
   <elementGuidId>d89f9d83-64d1-4725-b261-51ea94aa514a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbc_31983_26722.jpg-patch-image-reivew']//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3252303f-ca76-45d4-8d25-6ee6f95b3b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1746698258500</value>
      <webElementGuid>35be7a0c-f743-4840-84b3-4fdb3d3604a1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
