<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Morphology</name>
   <tag></tag>
   <elementGuidId>a5b73cc6-7e61-4a6b-9294-ef18077b36e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='plateleteMorphologyTab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#plateleteMorphologyTab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Morphology&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70c3b6eb-70a3-4ecd-a819-56db8636f339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view-selection-btn</value>
      <webElementGuid>958efb69-d47c-47e8-b26d-6027fe4a60a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plateleteMorphologyTab</value>
      <webElementGuid>25971eaa-cf78-49de-9fbf-9e8001800269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Morphology</value>
      <webElementGuid>fdb041e2-776d-406c-bb97-eaa904652f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plateleteMorphologyTab&quot;)</value>
      <webElementGuid>f5e691ac-b63c-43ae-9be7-4cac25bba8ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='plateleteMorphologyTab']</value>
      <webElementGuid>67452ea4-8ab5-42b8-9e8e-c2d2110706ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>bf7df154-f0b3-4e4c-a421-a4ea31e3fb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Count'])[1]/following::button[1]</value>
      <webElementGuid>197647aa-d518-4721-bb25-27c4231a3377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBC report could not be retrieved'])[1]/following::button[2]</value>
      <webElementGuid>363da42f-8014-4ae4-96f7-8624c2205aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cell name'])[1]/preceding::button[1]</value>
      <webElementGuid>082aca01-6ed5-4fe6-a000-32b518b6707d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avg Count/ 100X FOV'])[1]/preceding::button[1]</value>
      <webElementGuid>a8068e06-d67f-4226-aac7-04ee159686a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Morphology']/parent::*</value>
      <webElementGuid>e4443f18-48b1-4d69-a4f2-79f2cde11c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>b300950c-e33e-48b7-9e10-bc2fadf54d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'plateleteMorphologyTab' and (text() = 'Morphology' or . = 'Morphology')]</value>
      <webElementGuid>d62452c9-b081-4643-9d04-224857043ba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
