<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PBS_icon-img</name>
   <tag></tag>
   <elementGuidId>3d901e72-178d-40a4-ace8-6a8f64993a46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.icon-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;profile&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fe763d56-4316-4903-90f4-9c58ade1c126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-img</value>
      <webElementGuid>4e6363f5-2708-4eae-b5cf-8f229cd49521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/profile.svg</value>
      <webElementGuid>acfe0d9f-530a-4ae8-ac43-08429d15d475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>profile</value>
      <webElementGuid>e08ce4bb-52fb-4801-802e-ab1c7930e503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[@class=&quot;headerComponent_pbs-header__xqcbN&quot;]/div[2]/div[1]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeMedium sc-fYsHOw kEuSUN css-1yxmbwk&quot;]/img[@class=&quot;icon-img&quot;]</value>
      <webElementGuid>245e4320-a0cb-42fa-a2e8-ebd7324130e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/button/img</value>
      <webElementGuid>b4790228-8741-4063-a353-06cbcdfffce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='profile']</value>
      <webElementGuid>ec005ba0-b40d-48c2-925a-54584d66104b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>9b5a2ff2-a33c-42bf-b707-1e1e626e1cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/icons/profile.svg' and @alt = 'profile']</value>
      <webElementGuid>7a18f827-a00f-4bff-a863-f34804db8c3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
