<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cell nameWBCNeutrophils34.8Lymphocytes4.3Eosinophils10.9Monocytes19.6Basophils-Immature Granulocytes-Atypical CellsBlasts30.4Immature Eosinophils-Immature Basophils-Promonocytes-Prolymphocytes-Hairy Cells-Sezary Cell</name>
   <tag></tag>
   <elementGuidId>6baec790-06ce-4799-a605-80fb774d963f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-vtkee7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.css-vtkee7</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>51b678d6-da79-4287-928b-c0692976ebb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-vtkee7</value>
      <webElementGuid>b6f58cc9-6c95-4155-9141-21c175b4f973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cell name%WBCNeutrophils34.8Lymphocytes4.3Eosinophils10.9Monocytes19.6Basophils-Immature Granulocytes-Atypical Cells/Blasts30.4Immature Eosinophils-Immature Basophils-Promonocytes-Prolymphocytes-Hairy Cells-Sezary Cells-Plasma Cells-Others-Total100.0Non-WBCNRBC-Smudge Cells-</value>
      <webElementGuid>e54ed34b-1365-4e66-9303-90f13791077c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;review-body&quot;]/div[@class=&quot;review-selected-category&quot;]/div[1]/div[@class=&quot;reportSummary_container__0ygy0&quot;]/div[@class=&quot;reportSummary_pane__wyFf2&quot;]/div[@class=&quot;reportSummary_pane-flex__pDBLO&quot;]/div[@class=&quot;css-vtkee7&quot;]</value>
      <webElementGuid>50d674a4-315f-4f15-b3f1-8a1db1d74703</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>3bf1281d-d3c2-4efb-9afe-87dedfa87451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBC report could not be retrieved'])[1]/following::div[7]</value>
      <webElementGuid>65e7c576-2304-4572-8190-52b6cfe9af52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>49c6f6d1-d522-45a3-ae30-eed2a9064cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cell name%WBCNeutrophils34.8Lymphocytes4.3Eosinophils10.9Monocytes19.6Basophils-Immature Granulocytes-Atypical Cells/Blasts30.4Immature Eosinophils-Immature Basophils-Promonocytes-Prolymphocytes-Hairy Cells-Sezary Cells-Plasma Cells-Others-Total100.0Non-WBCNRBC-Smudge Cells-' or . = 'Cell name%WBCNeutrophils34.8Lymphocytes4.3Eosinophils10.9Monocytes19.6Basophils-Immature Granulocytes-Atypical Cells/Blasts30.4Immature Eosinophils-Immature Basophils-Promonocytes-Prolymphocytes-Hairy Cells-Sezary Cells-Plasma Cells-Others-Total100.0Non-WBCNRBC-Smudge Cells-')]</value>
      <webElementGuid>e0626791-01d4-4fd6-a670-be7c6149eb52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
