<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Platelets_patch-view</name>
   <tag></tag>
   <elementGuidId>e50766b6-1fc8-4799-b9bb-6c63534e3760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='patch-view']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#patch-view</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Patch view&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>365a4ff5-3e1a-4668-b640-8e62cdbb587f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>patch-view</value>
      <webElementGuid>22298deb-5c1f-4f37-bbef-dd306950c7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/views/patch-view-hover.svg</value>
      <webElementGuid>870ee446-3cf7-4a2e-8596-22e5f32edccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Patch view</value>
      <webElementGuid>f1c2a816-22bf-4040-bd6a-9957eb032ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Patch view</value>
      <webElementGuid>6d4850d1-2f77-4de1-ad8d-09c78b52b3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patch-view&quot;)</value>
      <webElementGuid>263d5570-6da1-43c4-9d41-b575b74a7189</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='patch-view']</value>
      <webElementGuid>38b22696-7bb3-4fee-9ed3-2eae05cb59d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/img</value>
      <webElementGuid>8bd542e4-07eb-48e4-8c3e-76bc7f37d62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Patch view']</value>
      <webElementGuid>ccd37293-b350-43f8-987a-5c5f8ff93f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/img</value>
      <webElementGuid>e3ab7a94-f8d4-4a48-871a-a6ff9e9da1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'patch-view' and @src = '/icons/views/patch-view-hover.svg' and @alt = 'Patch view']</value>
      <webElementGuid>c6da71fc-eaff-41dd-ab13-81670324d06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'patch-view' and @src = '/icons/views/patch-view-default.svg' and @alt = 'Patch view']</value>
      <webElementGuid>9c00ae41-e5c5-42d1-b218-a386cfa38b4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
