<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Microcytes</name>
   <tag></tag>
   <elementGuidId>2ddc9322-afc7-4d11-adfe-c166c3b717c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div/div/div[2]/table/tbody/tr/td/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cell-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Microcytes&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bebd4b7f-7f3a-424f-a9f6-68b11426b9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell-label </value>
      <webElementGuid>ba11e334-7cf6-474f-8698-24cbf02da799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Microcytes</value>
      <webElementGuid>6c09aab7-b7d0-41a8-9729-7e217f90c13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;review-body&quot;]/div[@class=&quot;review-selected-category&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;rbc-microscopic-left-pane&quot;]/div[1]/div[2]/table[@class=&quot;theame-table&quot;]/tbody[1]/tr[@class=&quot;selected-row valid&quot;]/td[1]/div[@class=&quot;cell-selection&quot;]/div[@class=&quot;cell-label&quot;]</value>
      <webElementGuid>23b9a478-41a9-4096-9982-370713a4c372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div/div/div[2]/table/tbody/tr/td/div/div</value>
      <webElementGuid>7e6c3ee4-04f9-406d-ae74-1eb8030b62ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/following::div[2]</value>
      <webElementGuid>a9337875-9fa4-4b54-8032-840a85ef5087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Count'])[1]/following::div[2]</value>
      <webElementGuid>c03719d6-e7fc-4db8-a8b7-06d2891668b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Macrocytes'])[1]/preceding::div[3]</value>
      <webElementGuid>eacf0f15-ef45-497f-ad5a-7d3124a1ebd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total number of RBCs counted for size based classification is 5549'])[1]/preceding::div[8]</value>
      <webElementGuid>5c6fd144-4a11-447a-9b02-fdb29df4da2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Microcytes']/parent::*</value>
      <webElementGuid>cf928a68-37da-4166-bdbe-1fcd54451ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div</value>
      <webElementGuid>f4f8c827-77cf-40a8-ade3-4e4b9fc92ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Microcytes' or . = 'Microcytes')]</value>
      <webElementGuid>3c0fdf8e-1f6c-47ca-8941-d2a176b8ad03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
