<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BranchBranch</name>
   <tag></tag>
   <elementGuidId>f32cecf4-2daa-497f-bb97-9e8b2e0d973e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-1']/app-filter/mat-dialog-content/form/div/div/mat-form-field[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-form-field.mat-form-field.ng-tns-c6-45.mat-primary.mat-form-field-type-mat-select.mat-form-field-appearance-legacy.mat-form-field-can-float.mat-form-field-has-label.mat-form-field-hide-placeholder.ng-untouched.ng-pristine.ng-valid.mat-focused > div.mat-form-field-wrapper > div.mat-form-field-flex > div.mat-form-field-infix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;BranchBranch&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>24118052-7cf5-4c05-85be-4be3ab9f6646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix</value>
      <webElementGuid>f2d52972-4b2a-4756-9920-ad7e90c101f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BranchBranch</value>
      <webElementGuid>cccb140a-16be-47d4-bd5e-9b38c27f5dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)/app-filter[@class=&quot;ng-star-inserted&quot;]/mat-dialog-content[@class=&quot;dialog-content mat-dialog-content&quot;]/form[@class=&quot;form-wrapper ng-pristine ng-valid ng-touched&quot;]/div[1]/div[@class=&quot;mobile-view-filer&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c6-45 mat-primary mat-form-field-type-mat-select mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-valid mat-focused&quot;]/div[@class=&quot;mat-form-field-wrapper&quot;]/div[@class=&quot;mat-form-field-flex&quot;]/div[@class=&quot;mat-form-field-infix&quot;]</value>
      <webElementGuid>17c16dc7-4a4e-41f8-bae0-62c800d53740</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/app-filter/mat-dialog-content/form/div/div/mat-form-field[2]/div/div/div</value>
      <webElementGuid>a32678d3-d6f2-4a85-a3a0-72d506e7af2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partner'])[1]/following::div[8]</value>
      <webElementGuid>ece02e81-0951-4853-b604-04af9f1a56fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SigTuple Technologies Pvt Ltd'])[1]/following::div[10]</value>
      <webElementGuid>6ed2e131-d257-4a09-a80f-119a00d68688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div/div/div</value>
      <webElementGuid>dbf97d7a-3a7f-42c2-97b0-b13fd2a8e40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BranchBranch' or . = 'BranchBranch')]</value>
      <webElementGuid>d939d451-135f-4c76-bb1b-e304770e6b00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
