<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Reviewed</name>
   <tag></tag>
   <elementGuidId>8bc9e9a2-ef02-411d-b6fa-a389d5f1227f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='report-type-popover']/div[3]/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Reviewed$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ea972f0b-d7c3-4684-9b3d-2ee7dc624bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reportTypeComponent_report-type-name__GZCsS</value>
      <webElementGuid>68cd7232-0c09-4247-80e0-d04d4764c301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reviewed</value>
      <webElementGuid>45e6aea7-90ce-41bb-ab20-30f434fce31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report-type-popover&quot;)/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation8 MuiPopover-paper css-1dmzujt&quot;]/div[1]/div[@class=&quot;reportTypeComponent_report-type-list-item__HcxAy&quot;]/div[@class=&quot;reportTypeComponent_report-type-name__GZCsS&quot;]</value>
      <webElementGuid>6bd41f21-4768-4bfc-9dae-de0f969ce932</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='report-type-popover']/div[3]/div/div[3]/div</value>
      <webElementGuid>8427bde0-510c-4055-a874-7d75ef679c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preparing'])[1]/following::div[2]</value>
      <webElementGuid>aaf3a97c-f43d-4523-9e35-57cc28abab1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready for review'])[2]/following::div[4]</value>
      <webElementGuid>b95645bb-d0ed-4c20-afa5-f2b268c0cfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div</value>
      <webElementGuid>fd62816f-8c1d-4b48-b6b0-78a5a45f7e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Reviewed' or . = 'Reviewed')]</value>
      <webElementGuid>bfa012c9-3596-4313-9179-c95aa33e5f55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
