<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>storage_parcentage</name>
   <tag></tag>
   <elementGuidId>23e4dca8-4afe-4df0-af6f-a87764e69fe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/section[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;185 GB of 769 GB used (24%)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf4c2252-ecc6-4cc9-afc2-46a567a35433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9609a69-8e85-43c1-ad29-0a34267dc476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>185 GB of 769 GB used (24%)</value>
      <webElementGuid>2e160ce0-55d9-4eef-9161-1d75bc6ef4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-10fsrl8&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-1y82ffr&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-9.5 css-70qs4m&quot;]/div[@class=&quot;status-container&quot;]/section[@class=&quot;storage-info&quot;]/div[@class=&quot;status-info-values&quot;]/div[@class=&quot;text&quot;]</value>
      <webElementGuid>8fab028e-4e46-475e-9a6c-48aa19222e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/section[2]/div/div</value>
      <webElementGuid>8bbdf113-82de-4af6-b7b3-d775f1b22f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[4]/following::div[2]</value>
      <webElementGuid>9fe7c3da-bf76-4892-965e-5d8f9b7d8057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platelet level limits'])[3]/following::div[4]</value>
      <webElementGuid>54ec6afe-bcff-453a-ad0e-e667bf194ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Storage type'])[1]/preceding::div[2]</value>
      <webElementGuid>b8d428d0-a37b-402c-995f-0474467a4c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='of']/parent::*</value>
      <webElementGuid>f691c479-7a61-4bd2-b258-4361b5d1aeaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div</value>
      <webElementGuid>3ae7bd74-6a34-4496-bc1a-f1c4584f4a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '185 GB of 769 GB used (24%)' or . = '185 GB of 769 GB used (24%)')]</value>
      <webElementGuid>b8e0c485-b29d-48d3-885e-0b97598cf5c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
