<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Morphology (2)</name>
   <tag></tag>
   <elementGuidId>23b69593-e0f9-4c7d-b202-5a2dc96594a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#plateleteMorphologyTab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='plateleteMorphologyTab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Morphology&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7fc475f6-2fef-491f-ad68-5cfb38e5745c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view-selection-btn</value>
      <webElementGuid>9d9c0f7b-3007-4c6c-a072-bb5be0c87823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plateleteMorphologyTab</value>
      <webElementGuid>b7e6568c-2c72-441e-8958-a1ae63b77f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Morphology</value>
      <webElementGuid>35d914ac-66e2-48aa-8379-ac9932ceaa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plateleteMorphologyTab&quot;)</value>
      <webElementGuid>a51aa903-015e-4291-9f83-be9e1cea7418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='plateleteMorphologyTab']</value>
      <webElementGuid>eae571e6-1c63-4cb0-a97a-fac63481db54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>adc245cf-2f34-469f-8524-785b3bfd71fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Count'])[1]/following::button[1]</value>
      <webElementGuid>d479331a-fe27-405f-a643-be72c7650e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBC report could not be retrieved'])[1]/following::button[2]</value>
      <webElementGuid>a71a6e3f-d247-4c58-ac3e-284dcea4fb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cell name'])[1]/preceding::button[1]</value>
      <webElementGuid>8f4241e5-de37-48c8-ac0c-aacbe602e765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avg Count/ 100X FOV'])[1]/preceding::button[1]</value>
      <webElementGuid>1cbe9d46-2294-4c76-a174-76813ffeb118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Morphology']/parent::*</value>
      <webElementGuid>ead19b80-7fc5-477f-a2e0-2bb3f9871705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>3315ba56-b850-4695-9e0a-13419dadb336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'plateleteMorphologyTab' and (text() = 'Morphology' or . = 'Morphology')]</value>
      <webElementGuid>99064c8a-8c2a-42be-8b3a-99f46ac06e95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
