<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Image settings_default-patch  patch-foc_a6a738</name>
   <tag></tag>
   <elementGuidId>0357eabf-ee96-425b-b297-f6015e3e5485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.default-patch.patch-focus-mode.show-subcell-lable.enabled.patch-menu-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id=&quot;split-view&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;wbc_33398_18694\.jpg-patch-image-reivew&quot;] div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a445f9f6-36dd-479d-9fd4-c972e5790c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> default-patch  patch-focus-mode show-subcell-lable  enabled patch-menu-container</value>
      <webElementGuid>ab818288-2c17-4f7d-b972-8b1aa9007095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbc_33398_18694.jpg-patch-image-reivew&quot;)/div[@class=&quot;patch-img-container patch-focus-mode&quot;]/div[@class=&quot;default-patch  patch-focus-mode show-subcell-lable  enabled patch-menu-container&quot;]</value>
      <webElementGuid>f938401c-43f4-4c12-ad6d-686d76822fc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbc_33398_18694.jpg-patch-image-reivew']/div/div</value>
      <webElementGuid>6e0755e3-704b-4851-ab66-c74cf1643025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image settings'])[1]/following::div[9]</value>
      <webElementGuid>44796dca-18b9-4218-abf9-17a25d8f2b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of WBCs counted is &lt;200. Differential count might not be accurate'])[1]/following::div[15]</value>
      <webElementGuid>cd527877-c5d4-41e1-88ad-2e925d3089b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>5f026992-2650-4adb-9c5b-8c45e135492e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
