<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Platelets_split-view (3)</name>
   <tag></tag>
   <elementGuidId>2643f1a1-4781-4711-b02e-7272217453c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#split-view</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='split-view']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Split view&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c7faf82e-f49a-42c5-bc9c-1484c1381e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>split-view</value>
      <webElementGuid>06103ff6-a678-4024-97de-0fe05b6ddab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/views/split-view-hover.svg</value>
      <webElementGuid>ca444d96-88fa-428c-997e-371bec85a696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Split view</value>
      <webElementGuid>2dd96f1f-3466-43b8-98ff-3afa1a2b1dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Split view</value>
      <webElementGuid>fd4522f7-8afd-4166-b665-b95da4c46dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;split-view&quot;)</value>
      <webElementGuid>b37e66ca-ea58-437a-9a6f-d68e804e5054</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='split-view']</value>
      <webElementGuid>34d4631a-2857-4a13-8c67-85ab5457d687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/img[2]</value>
      <webElementGuid>5bdae839-025b-429f-8f2d-3c1b612bb80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Split view']</value>
      <webElementGuid>55642b21-6747-446f-a3a4-1e1c9504196e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>04a8fa29-e23d-467d-8433-f81a587a104e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'split-view' and @src = '/icons/views/split-view-hover.svg' and @alt = 'Split view']</value>
      <webElementGuid>b9d2979c-27a7-4f41-a42c-b8329e3e3c72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
