<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Disclaimer</name>
   <tag></tag>
   <elementGuidId>2808a43f-8f87-4436-b555-e05225f16e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.bottomDisclaimer_container__text__y7BCT.bottomDisclaimer_container__text--bold__qk5JT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Disclaimer' or . = 'Disclaimer')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Disclaimer:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bcfcb477-5c03-4d04-9f27-bbb2ec401d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bottomDisclaimer_container__text__y7BCT bottomDisclaimer_container__text--bold__qk5JT</value>
      <webElementGuid>c8c6739b-0dcd-4144-b8a1-67ab90fefd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disclaimer:  </value>
      <webElementGuid>d6067c48-cb31-4287-840c-afb69f078696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;bottomDisclaimer_container__XJPK2&quot;]/span[@class=&quot;bottomDisclaimer_container__text__y7BCT bottomDisclaimer_container__text--bold__qk5JT&quot;]</value>
      <webElementGuid>b346a7ad-0139-421d-8250-45f8cd09a470</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/span</value>
      <webElementGuid>54c1019a-7e05-4f0c-b683-6aa50a3bdbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[1]/following::span[1]</value>
      <webElementGuid>ea5db719-5928-467f-a421-01bcad8bccbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='–'])[1]/following::span[2]</value>
      <webElementGuid>a206ca0c-44e4-4dc2-9e54-70608c9a8ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disclaimer']/parent::*</value>
      <webElementGuid>c20ab88f-eef4-4280-961a-a8f39c810300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>6c739757-d76c-4afc-8a8b-39efcd6a9def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Disclaimer:  ' or . = 'Disclaimer:  ')]</value>
      <webElementGuid>7ec5b55f-f206-4f6f-88b0-fee9c02d89a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image settings'])[1]/following::span[1]</value>
      <webElementGuid>726cb739-3249-4d6f-8d1f-6519a1136c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total number of RBCs counted for size based classification is 5328'])[1]/following::span[2]</value>
      <webElementGuid>350e83eb-4fb4-4fc5-91fd-34f35f78f063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[5]/following::span[1]</value>
      <webElementGuid>773f77e2-23ca-4c90-8475-202e50569a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[5]/following::span[2]</value>
      <webElementGuid>b9c82371-05d6-4981-ad7e-dc9aa41b06ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of WBCs counted is &lt;200. Differential count might not be accurate'])[1]/following::span[2]</value>
      <webElementGuid>a90477b8-784d-42fc-bc4e-49aafe29e2ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
