<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_(UTC0000) AfricaDakar</name>
   <tag></tag>
   <elementGuidId>0628bc6a-d862-4ee8-ac4d-a668aee22ef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#assigned_to-option-17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='assigned_to-option-17']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;(UTC+00:00) Africa/Dakar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>896d2cc6-130c-4c84-b488-200b2558a12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d32bbdb2-21c3-4fa3-af2e-cf4e18419547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7c56ff3f-4abf-4d12-925e-d4ff7b71f2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assigned_to-option-17</value>
      <webElementGuid>34c65dbe-d72a-44da-83d5-036866d0fec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>3e9b99d3-bf7d-41b7-b6ba-5accecd607b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8d048ca-c05a-4823-9827-00c50ccfe901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f109de3e-723c-4ad2-92fd-dccfefb9c9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>beb665a9-15cc-46dd-9523-7b3449dd6cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(UTC+00:00) Africa/Dakar</value>
      <webElementGuid>240ea327-d0be-4860-a828-c1bd9c6632fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assigned_to-option-17&quot;)</value>
      <webElementGuid>a5385dac-3763-4c7d-a24e-918e290530d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='assigned_to-option-17']</value>
      <webElementGuid>9474b293-3a2e-4156-8664-dda130fd61e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='assigned_to-listbox']/li[18]</value>
      <webElementGuid>2517962c-228c-473b-8195-053b3637aab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(UTC+00:00) Africa/Conakry'])[1]/following::li[1]</value>
      <webElementGuid>165efe4c-48bf-468f-aa24-1c849dc7e369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(UTC+02:00) Africa/Ceuta'])[1]/following::li[2]</value>
      <webElementGuid>da246119-f2ab-488f-a2ee-32dd8cf8fb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(UTC+03:00) Africa/Dar_es_Salaam'])[1]/preceding::li[1]</value>
      <webElementGuid>608d71fc-8de3-4cd7-bb18-4148d1a9e28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(UTC+03:00) Africa/Djibouti'])[1]/preceding::li[2]</value>
      <webElementGuid>0c2afc2e-03f1-4c3f-9df0-6cd487bce5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(UTC+00:00) Africa/Dakar']/parent::*</value>
      <webElementGuid>bef82d0b-276c-4cee-965c-cf60a5a806ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[18]</value>
      <webElementGuid>03b93bf8-fc42-452b-8304-2cfbde7e3248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'assigned_to-option-17' and (text() = '(UTC+00:00) Africa/Dakar' or . = '(UTC+00:00) Africa/Dakar')]</value>
      <webElementGuid>cb585737-d83d-4676-aeb9-14fbe86856e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
