<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PBS</name>
   <tag></tag>
   <elementGuidId>d660b659-0375-4f08-b637-7f82821e79b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.headerComponent_pbs-text__UU-3l</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;PBS&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ba8fb267-44ac-4629-bcc3-4a6da62e111f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headerComponent_pbs-text__UU-3l</value>
      <webElementGuid>d19bf17c-ef11-4582-a9db-c7bf3484bf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PBS</value>
      <webElementGuid>b6073806-730b-413d-82f3-42aab05d00d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[@class=&quot;headerComponent_pbs-header__xqcbN&quot;]/div[@class=&quot;headerComponent_pbs-header__left__SEZ4A&quot;]/span[@class=&quot;headerComponent_pbs-text__UU-3l&quot;]</value>
      <webElementGuid>15e179c0-94fe-4cc5-94ca-936fd3e668f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/span</value>
      <webElementGuid>334fd98d-a47d-4025-bb17-23794d5dde6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear filters'])[1]/preceding::span[2]</value>
      <webElementGuid>37873963-8caf-4e8c-bfc3-c1036b301ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My reports'])[1]/preceding::span[3]</value>
      <webElementGuid>0bf6e603-49f1-4c79-9949-d28eaff05669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>d5e1b895-dcca-437a-9c4e-b8a5afb4e78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PBS' or . = 'PBS')]</value>
      <webElementGuid>9fa4ee55-1ea2-4d75-a7a8-3bdf2e797b72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
