<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas__ol-layer</name>
   <tag></tag>
   <elementGuidId>d139a42f-73bf-4261-a25a-1d753ddcc375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ol-overviewmap-map > div.ol-viewport > div.ol-unselectable.ol-layers > canvas.ol-layer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id=&quot;pbs-volumeViewport&quot;]//canvas)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^‹$/ >> canvas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>6042943f-7cd7-4679-b181-a7b655f3ac69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>264</value>
      <webElementGuid>f41121cc-c80b-422e-b3b6-6b78b54006d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>434</value>
      <webElementGuid>34d9022b-abf7-4c66-89b2-440bee5d2323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ol-layer</value>
      <webElementGuid>69fe3363-3d79-490a-957b-e8b88d656b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pbs-volumeViewport&quot;)/div[@class=&quot;ol-viewport&quot;]/div[@class=&quot;ol-overlaycontainer-stopevent&quot;]/div[@class=&quot;ol-overviewmap ol-unselectable ol-control&quot;]/div[@class=&quot;ol-overviewmap-map&quot;]/div[@class=&quot;ol-viewport&quot;]/div[@class=&quot;ol-unselectable ol-layers&quot;]/canvas[@class=&quot;ol-layer&quot;]</value>
      <webElementGuid>32f7041c-1965-4806-b5f1-c0b5ad109723</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pbs-volumeViewport']/div/div[3]/div[5]/div/div/div/canvas</value>
      <webElementGuid>92e3b1bd-051e-4be0-8893-ce91b4f067a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/canvas</value>
      <webElementGuid>56507ae1-7e0e-41c9-b1d1-cb86d8ff7338</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
