<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Image settings_default-patch  patch-foc_a6a738</name>
   <tag></tag>
   <elementGuidId>4add48b8-35ad-45c2-81fd-e4633f45068e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.default-patch.patch-focus-mode.show-subcell-lable.enabled.patch-menu-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wbc_56770_9802.jpg-patch-image-reivew']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;wbc_56770_9802\.jpg-patch-image-reivew&quot;] div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>777e3c70-5ff1-4b35-a7d0-ff392bcd40bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> default-patch  patch-focus-mode show-subcell-lable  enabled patch-menu-container</value>
      <webElementGuid>0d1fda94-202f-4c83-b126-3ac57b7ad298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbc_56770_9802.jpg-patch-image-reivew&quot;)/div[@class=&quot;patch-img-container patch-focus-mode&quot;]/div[@class=&quot;default-patch  patch-focus-mode show-subcell-lable  enabled patch-menu-container&quot;]</value>
      <webElementGuid>ae7b42cd-1b9f-48c7-8b97-75d2721621e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wbc_56770_9802.jpg-patch-image-reivew']/div/div</value>
      <webElementGuid>f3e200f7-7a1d-4642-aebf-f578dd34d841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image settings'])[1]/following::div[9]</value>
      <webElementGuid>be063266-61d5-49a7-9f85-4323fe3d1a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of WBCs counted is &lt;200. Differential count might not be accurate'])[1]/following::div[15]</value>
      <webElementGuid>3beae91f-9a4f-456c-8665-19df3f4663cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>c62b3b21-ff87-41d7-96f9-7d491b4ce9c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
