<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ScanDate_in_image</name>
   <tag></tag>
   <elementGuidId>c0d3d3cc-1db7-47d0-afb4-95ba7dba6b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.time</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='specimen-info']/div[3]/div/div[2]/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;28-Apr-2025, 12:29 PM (IST)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5574757b-f537-47fd-a3ad-c4b398d220e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>fbe9ba35-24a5-4cea-817a-39cfcb21989b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>28-Apr-2025, 12:29 PM (IST)</value>
      <webElementGuid>52a23ba6-5f3b-4bfc-b7ab-7c087d0dd840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;specimen-info&quot;)/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation16 MuiDrawer-paper MuiDrawer-paperAnchorLeft css-wf16b5&quot;]/div[1]/div[@class=&quot;slideInfoComponent_drawer__body__abbGp&quot;]/div[@class=&quot;slideInfoComponent_drawer__body-info__rBKp8&quot;]/div[@class=&quot;slideInfoComponent_drawer__body-info-item__vTpE3 slideInfoComponent_drawer__body-info-item--half-width__z8fuU&quot;]/div[@class=&quot;time&quot;]</value>
      <webElementGuid>af453c53-6245-4db7-b099-a9274239ac6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='specimen-info']/div[3]/div/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>c402fff1-b0b9-4fa6-a3b9-5827f556022a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scanned on'])[1]/following::div[1]</value>
      <webElementGuid>4de9ed8f-4593-4242-a7dc-0af3e159bb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sanadmin'])[1]/following::div[2]</value>
      <webElementGuid>e62bdbac-a87f-452c-8cb1-826edf2e0f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='28-Apr-2025, 12:29 PM (IST)']/parent::*</value>
      <webElementGuid>165ac09e-4547-4531-ba58-e1270979b58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>caa19d14-99df-46d2-9c14-4d1f230b5cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '28-Apr-2025, 12:29 PM (IST)' or . = '28-Apr-2025, 12:29 PM (IST)')]</value>
      <webElementGuid>de3ec250-845f-4c4b-beb1-816aad2d3bfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
