<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Platelet level limits</name>
   <tag></tag>
   <elementGuidId>f7a044ef-a660-4056-81f0-dbdf14899d51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='dashboard-tabs5'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiCollapse-root.MuiCollapse-vertical.MuiCollapse-entered.css-c4sutr > div.MuiCollapse-wrapper.MuiCollapse-vertical.css-hboir5 > div.MuiCollapse-wrapperInner.MuiCollapse-vertical.css-8atqhb > #panel1d-content > div.MuiAccordionDetails-root.css-1nngiw2 > div.MuiTabs-root.MuiTabs-vertical.css-19u5qy2 > div.MuiTabs-scroller.MuiTabs-fixed.css-1anid1y > div.MuiTabs-flexContainer.MuiTabs-flexContainerVertical.css-j7qwjs > #dashboard-tabs5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Platelet level limits&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>393b42af-158b-47a8-ab39-2ae6eecb29a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary css-1ma9xb4</value>
      <webElementGuid>0f3e568c-6977-4ea0-a410-5b737e904e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6b84c756-118f-482b-bbcd-60318bf62ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d54d022-f947-4e67-852b-e148a6968024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>99e66878-21df-4bb1-9199-ab8b946eecb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f67173d9-1956-45ac-a94a-ad79dd7dd8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dashboard-tabs5</value>
      <webElementGuid>ab29b459-11ea-485a-9c90-721acf333d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Platelet level limits</value>
      <webElementGuid>911e8b72-baa9-4387-be9e-131bb8134eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-10fsrl8&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-1y82ffr&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-2.5 css-uwfszu&quot;]/div[@class=&quot;sc-dlfmHC hTojMe&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiAccordion-root Mui-expanded css-o11krc&quot;]/div[@class=&quot;MuiCollapse-root MuiCollapse-vertical MuiCollapse-entered css-c4sutr&quot;]/div[@class=&quot;MuiCollapse-wrapper MuiCollapse-vertical css-hboir5&quot;]/div[@class=&quot;MuiCollapse-wrapperInner MuiCollapse-vertical css-8atqhb&quot;]/div[@id=&quot;panel1d-content&quot;]/div[@class=&quot;MuiAccordionDetails-root css-1nngiw2&quot;]/div[@class=&quot;MuiTabs-root MuiTabs-vertical css-19u5qy2&quot;]/div[@class=&quot;MuiTabs-scroller MuiTabs-fixed css-1anid1y&quot;]/div[@class=&quot;MuiTabs-flexContainer MuiTabs-flexContainerVertical css-j7qwjs&quot;]/button[@id=&quot;dashboard-tabs5&quot;]</value>
      <webElementGuid>b296141e-32ec-47f3-b359-d0103e618d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='dashboard-tabs5'])[3]</value>
      <webElementGuid>ade6c677-da54-425c-8f70-c538ed94bda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='panel1d-content']/div/div/div/div/button[6])[3]</value>
      <webElementGuid>009b1849-7ac5-4063-93d5-ef97c3449949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RBC grade limits'])[3]/following::button[1]</value>
      <webElementGuid>3624cc17-a027-44ae-ae0a-546773eaebad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RBC diameter limits'])[3]/following::button[2]</value>
      <webElementGuid>c07b9055-5daf-42c2-af85-864eeac9e26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[4]/preceding::button[1]</value>
      <webElementGuid>c9d36e9d-1fd9-4aa1-887c-3f8a7a6e8eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div/div/button[6]</value>
      <webElementGuid>9cc23d81-e7ee-4679-8093-338dc2e04fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dashboard-tabs5' and (text() = 'Platelet level limits' or . = 'Platelet level limits')]</value>
      <webElementGuid>1c46722d-e137-44a8-8846-aedc1f6d1574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
