<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Password</name>
   <tag></tag>
   <elementGuidId>fa49c06f-f5a8-4796-a221-c18426ab2965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//p[@id='modal-modal-description'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > #modal-modal-description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>p >> internal:has-text=&quot;Password&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a2067ca5-7292-48cb-b48a-ebb2bf512f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 css-yg30e6</value>
      <webElementGuid>c9c72ae7-75ed-4ca7-904b-e7a7b5476c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-modal-description</value>
      <webElementGuid>854cb733-84e3-48be-b523-fca2b172bb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>dcbc345f-d8de-47f9-86fd-a396b70d01a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiModal-root css-1ydukw5&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 css-1y8e9mf&quot;]/div[@class=&quot;css-fpoild&quot;]/div[@class=&quot;modal-content&quot;]/div[3]/p[@id=&quot;modal-modal-description&quot;]</value>
      <webElementGuid>134958c9-1590-426d-b86c-56cecace80bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//p[@id='modal-modal-description'])[3]</value>
      <webElementGuid>b878cf8d-835f-4315-9176-28fa6fc4dd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oriennnto'])[2]/following::p[1]</value>
      <webElementGuid>a3f04a9d-9e8a-4481-b820-d5043bf807ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share the Credentials'])[1]/following::p[3]</value>
      <webElementGuid>cee98f16-071e-4de2-aa5b-9a46ced1883a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='********'])[1]/preceding::p[1]</value>
      <webElementGuid>126b3c4b-c22f-4ffb-800f-54b4e02d01d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::p[1]</value>
      <webElementGuid>e245530c-138d-40fb-8298-286d81611261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>5a3f2774-b3f1-4ea9-840d-ff4754798c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'modal-modal-description' and (text() = 'Password' or . = 'Password')]</value>
      <webElementGuid>2b9e2979-4c09-4f7d-bbdf-5a7f330b9bb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
